### ISSUE TITLE
Webhook fails with key error

### ISSUE THREAD

**Issue by BenMatheja** [BenMatheja/todoist-serverless-lambda#1]
https://github.com/BenMatheja/todoist-serverless-lambda/blob/af30c3c0034451f5b09570554ebc2d5eab732c72/handlers/todoist_handler.py#L51

```
'x-todoist-hmac-sha256': KeyError
Traceback (most recent call last):
  File "/var/task/handlers/todoist_handler.py", line 73, in handle_event
    delivered_hmac = extract_delivered_hmac(event)
  File "/var/task/handlers/todoist_handler.py", line 51, in extract_delivered_hmac
    return event.get('headers')['x-todoist-hmac-sha256']
KeyError: 'x-todoist-hmac-sha256'
```
Output from Lambda Event below
```
[INFO]	2020-06-13T06:13:12.757Z	9de60675-40f2-4c82-9e7a-9ac5d029a896	EVENT: {'resource': '/todoist/webhook', 'path': '/todoist/webhook', 'httpMethod': 'POST', 'headers': 'User-Agent': 'Todoist-Webhooks',  'X-Todoist-Delivery-ID': ['8c7644eb-75f9-4cb0-88a2-49bdcc7b1b49'], 'X-Todoist-Hmac-SHA256': ['Hz1b1A2Gfb5CCOtacD80kQV1AWqd2ZbOXZXp/Z5A1MY=']}, 
```

**Comment by BenMatheja** [comment]
Got resolved by itself - somehow
